iaer/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path
from django.urls import include
from rest_framework import renderers
from rest_framework.urlpatterns import format_suffix_patterns

# api
from myproject import settings
from iaer.views.views import about_us_view, RedEnvelopeViewSet, IaerViewSet, CategoryViewSet, FundViewSet, AboutViewSet
from iaer.views.user_views import UserViewSet, login_view, send_verify_code_view, reset_password_with_verify_code_view
from iaer.views.user_views import api_root
from iaer.views.statistics_views import StatisticsCategoryViewSet, StatisticsDateViewSet
from iaer.views.setting_views import SettingViewSet

# website
from iaer.views.webviews import index
from iaer.views.webviews import UserListView
from iaer.views.webviews import IaerListView
from iaer.views.webviews import IaerDeleteView
from iaer.views.webviews import IaerDetailView
from iaer.views.webviews import IaerCreateView


api_user_list = UserViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

api_user_detail = UserViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

api_red_envelope_list = RedEnvelopeViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

api_red_envelope_detail = RedEnvelopeViewSet.as_view({
    'get': 'retrieve',
    'delete': 'destroy'
})

api_iaer_list = IaerViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

api_iaer_detail = IaerViewSet.as_view({
    'get': 'retrieve',
    'delete': 'destroy'
})

api_category_list = CategoryViewSet.as_view({
    'get': 'list',
})

api_statistics_category = StatisticsCategoryViewSet.as_view({
    'get': 'list',
})

api_statistics_date = StatisticsDateViewSet.as_view({
    'get': 'list',
})

api_fund_list = FundViewSet.as_view({
    'get': 'list',
})

api_setting_detail = SettingViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
})

api_about_detail = AboutViewSet.as_view({
    'get': 'retrieve',    
})

# user_login = LoginViewSet.as_view({
#     'post': 'retrieve',
# })

user_highlight = UserViewSet.as_view({
    'get': 'highlight'
}, renderer_classes=[renderers.StaticHTMLRenderer])

app_name = 'iaer'
api_urlpatterns = [
    path('', api_root, name='api-index'),
    path('users/', api_user_list, name='api-user-list'),
    path('users/<int:pk>/', api_user_detail, name='api-user-detail'),
    path('users/<int:pk>/highlight/', user_highlight, name='api-user-highlight'),
    path('user/login/', login_view, name='api-user-login'),
    path('user/send_verify_code/', send_verify_code_view, name='api-send-verify-code'),
    path('user/reset_password/', reset_password_with_verify_code_view, name='api-reset-password-with-verify-code'),
    path('about_us/', about_us_view, name='api-about-us'),
    path('envelopes/', api_red_envelope_list, name='api-red-envelope-list'),
    path('envelopes/<int:pk>/', api_red_envelope_detail, name='api-red-envelope-detail'),
    path('iaers/', api_iaer_list, name='api-iaer-list'),
    path('iaers/<int:pk>/', api_iaer_detail, name='api-iaer-detail'),
    path('categories/', api_category_list, name='api-category-list'),
    path('statistics/category/', api_statistics_category, name='api-statistics-category'),
    path('statistics/date/', api_statistics_date, name='api-statistics-date'),
    path('funds/', api_fund_list, name='api-fund-list'),
    path('setting/', api_setting_detail, name='api-setting-detail'),
    path('about/', api_about_detail, name='api-about-detail'),
]

urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='users'),
    path('users/<int:pk>/', IaerListView.as_view(), name='iaer-list'),
    path('iaers/add', IaerCreateView.as_view(), name='iaer-add'),
    path('iaers/<int:pk>/', IaerDetailView.as_view(), name='iaer-detail'),
    path('iaers/delete/<int:pk>/', IaerDeleteView.as_view(), name='iaer-delete'),
    path('api/', include(api_urlpatterns)),
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('photo/', include('photo.urls')),
    path('iaer/', include('iaer.urls')),
    path('tools/', include('tools.urls')),
    path('', include('iaer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
import os

from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import classification
from .views import index
from .views import reset
from .views import UserListView
from .views import PhotoListView
from .views import PhotoYearArchiveView
from .views import PhotoMonthArchiveView
from .views import GalleryView
from .views import GalleryListView

from myproject.settings import BASE_DIR


app_name = 'photo'
urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='users'),
    path('reset/<int:user_id>/', reset, name='reset'),
    path('classification/<int:user_id>/', classification, name='classification'),
    path('users/<int:pk>/', PhotoListView.as_view(), name='user-gallery'),
    path('users/<int:pk>/<int:year>/', PhotoYearArchiveView.as_view(), name='gallery-year-archive'),
    path('users/<int:pk>/<int:year>/<int:month>/', PhotoMonthArchiveView.as_view(month_format='%m'), name='gallery-month-archive'),
    path('galleries/', GalleryListView.as_view(), name='galleries'),
    path('galleries/<slug:title>/', GalleryView.as_view(), name='gallery'),
] + static(settings.MEDIA_URL, document_root=os.path.join(BASE_DIR, 'photo', 'media'))

photo/models.py
import os
import pdb

from django.db import models
from PIL import Image
from dateutil.relativedelta import relativedelta
from datetime import datetime
from shutil import copyfile
from django.contrib.postgres.fields import ArrayField

from myproject.settings import MEDIA_URL
from myproject.settings import PHOTO_DIR

THUMBNAIL_DIR = "thumbnail"
DEFAULT_THUMBNAIL_SIZE = 160

class User(models.Model):
    auth_user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    phone = models.CharField(max_length=30, blank=True, null=True)
    gender = models.PositiveSmallIntegerField(default=2) #0 for boy, 1 for girl, 2 for others
    profile = models.CharField(max_length=200, blank=True, null=True)
    user_type = models.PositiveSmallIntegerField(default=0)
    region = models.CharField(max_length=100, blank=True, null=True)
    locale = models.CharField(max_length=10, blank=True, null=True)
    whats_up = models.CharField(max_length=200, blank=True, null=True)
    zone = models.CharField(max_length=50, blank=True, null=True)
    birthday = models.DateTimeField(blank=True, null=True)
    hobbies = models.TextField(max_length=500, blank=True, null=True)
    highlighted = models.TextField(blank=True, null=True)
    created = models.DateTimeField(editable=False, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)
    is_email_activate = models.BooleanField(default=False)
    is_phone_activate = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.auth_user.username

class Photo(models.Model):
    # exif
    exif_image_width = models.PositiveSmallIntegerField('image width', blank=True, null=True)
    exif_image_height = models.PositiveSmallIntegerField('image height', blank=True, null=True)
    exif_make = models.CharField('make', max_length=50, blank=True, null=True)
    exif_model = models.CharField('model', max_length=100, blank=True, null=True)
    exif_lens_make = models.CharField('lens make', max_length=50, blank=True, null=True)
    exif_lens_model = models.CharField('lens model', max_length=100, blank=True, null=True)
    exif_version = models.CharField('exif version', max_length=10, blank=True, null=True)
    exif_subject_location = models.CharField('subject location', max_length=30, blank=True, null=True)
    exif_datetime = models.DateField('datetime', blank=True, null=True)
    exif_datetime_original = models.DateField('datetime original', blank=True, null=True)
    exif_datetime_digitized = models.DateField('datetime digitized', blank=True, null=True)
    # custom
    user = models.ForeignKey(User, verbose_name='user', related_name='photos', blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField('name', max_length=50)
    directory = models.CharField('directory', max_length=200)
    labels = ArrayField(models.CharField('label', max_length=50), blank=True, null=True)
    sub_dir = models.CharField('sub_dir', max_length = 10)
    duration = models.DurationField('duration')
    sha1sum = models.CharField('sha1sum', max_length=50)
    category = models.PositiveSmallIntegerField('category', default = 0)
    version = models.PositiveSmallIntegerField('version', default = 0)
    description = models.TextField('description', max_length=1024, blank=True, null=True)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    modify_date = models.DateTimeField('date modified', auto_now=True)

    def get_age_description(self):
        delta = self._get_relativedelta()
        description = ""

        if delta.years > 0:
            description += str(delta.years) + "年"
        if delta.months > 0:
            description += str(delta.months) + "个月"
        if delta.days > 0:
            description += str(delta.days) + "天"

        if description:
            return description
        else:
            return "出生日"

    def get_sub_dir_description(self):
        return self.sub_dir.replace("M", "个月").replace("Y", "岁")

    def get_url(self):
        return os.path.join(self.directory, self.name)

    def get_thumbnail_directory(self):
        return os.path.join(self.directory, THUMBNAIL_DIR)

    def get_thumbnail_url(self):
        return os.path.join(self.get_thumbnail_directory(), self.name)

    def set_photo_directory(self, src_file_name, src_file_path, dest_dir_name):
        photo_dir = os.path.abspath(os.path.dirname(__file__)) + \
                os.path.join(MEDIA_URL, PHOTO_DIR, dest_dir_name)
        delta = self._get_relativedelta()
        self.duration = self._get_timedelta() 

        if delta.years == 0:
            dest_sub_dir = str(delta.months + 1) + "M"
        else:
            dest_sub_dir = str(delta.years + 1) + "Y"

        self.sub_dir = dest_sub_dir

        img_dir = os.path.join(photo_dir, dest_sub_dir)
        os.makedirs(os.path.join(img_dir, THUMBNAIL_DIR), exist_ok=True)
        os.rename(src_file_path, os.path.join(img_dir, src_file_name))
        #copyfile(src_file_path, os.path.join(img_dir, src_file_name))
        self.directory = os.path.join(MEDIA_URL, PHOTO_DIR, dest_dir_name, dest_sub_dir)

    def save(self, *args, **kwargs):
        self._save_default_thumbnail_image()
        super(Photo, self).save(*args, **kwargs)
    
    def _get_relativedelta(self):
        return relativedelta(datetime.strptime(
            str(self.exif_datetime_original), '%Y-%m-%d'), self.user.birthday)

    def _get_timedelta(self):
        return datetime.strptime(str(self.exif_datetime_original), '%Y-%m-%d') \
            - self.user.birthday

    def _save_thumbnail_image(self, height = DEFAULT_THUMBNAIL_SIZE, width = DEFAULT_THUMBNAIL_SIZE):
        current_dir = os.path.abspath(os.path.dirname(__file__))
        if os.path.exists(current_dir + self.get_thumbnail_url()):
            print("File already exists")
            return

        if height > 0:
            rate = float(self.exif_image_height) / height
            width = float(self.exif_image_width) / rate
        else:
            rate = float(self.exif_image_width) / width
            height = float(self.exif_image_height) / rate

        url = self.get_url()
        size = int(width), int(height) 
        im = Image.open(current_dir + self.get_url())
        im.thumbnail(size, Image.ANTIALIAS)
        im.save(current_dir + self.get_thumbnail_url(), "JPEG")
        im.close()

    def _save_default_thumbnail_image(self):
        return self._save_thumbnail_image(DEFAULT_THUMBNAIL_SIZE, 0)

    def __str__(self):
        return self.name

photo/models/abstract_model.py
from django.db import models


DATE_FORMAT_CHOICES = (
            (u'0', u'不显示'),
            (u'1', u'显示日期'),
            (u'2', u'显示年龄'),
            (u'3', u'显示日期和年龄'),
        )

class Exif(models.Model):
    exif_image_width = models.PositiveSmallIntegerField('image width', blank=True, null=True)
    exif_image_height = models.PositiveSmallIntegerField('image height', blank=True, null=True)
    exif_make = models.CharField('make', max_length=50, blank=True, null=True)
    exif_model = models.CharField('model', max_length=100, blank=True, null=True)
    exif_lens_make = models.CharField('lens make', max_length=50, blank=True, null=True)
    exif_lens_model = models.CharField('lens model', max_length=100, blank=True, null=True)
    exif_version = models.CharField('exif version', max_length=10, blank=True, null=True)
    exif_subject_location = models.CharField('subject location', max_length=30, blank=True, null=True)
    exif_datetime = models.DateField('datetime', blank=True, null=True)
    exif_datetime_original = models.DateField('datetime original', blank=True, null=True)
    exif_datetime_digitized = models.DateField('datetime digitized', blank=True, null=True)

    class Meta:
        abstract = True

photo/models/user_model.py
from django.db import models

from collections import defaultdict

from .abstract_model import DATE_FORMAT_CHOICES


class UserQuerySet(models.QuerySet):
    def boys(self):
        return self.filter(gender = 0)

    def girls(self):
        return self.filter(gender = 1)


class UserManager(models.Manager):
    def get_queryset(self):
        return UserQuerySet(self.model, using = self._db)

    def boys(self):
        return self.get_queryset().boys()

    def girls(self):
        return self.get_queryset().girls()


class User(models.Model):
    auth_user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    phone = models.CharField(max_length=30, blank=True, null=True)
    gender = models.PositiveSmallIntegerField(default=2) #0 for boy, 1 for girl, 2 for others
    profile = models.CharField(max_length=200, blank=True, null=True)
    date_format = models.CharField(max_length=50, choices=DATE_FORMAT_CHOICES, default='0')
    user_type = models.PositiveSmallIntegerField(default=0)
    region = models.CharField(max_length=100, blank=True, null=True)
    locale = models.CharField(max_length=10, blank=True, null=True)
    whats_up = models.CharField(max_length=200, blank=True, null=True)
    zone = models.CharField(max_length=50, blank=True, null=True)
    birthday = models.DateTimeField(blank=True, null=True)
    hobbies = models.TextField(max_length=500, blank=True, null=True)
    highlighted = models.TextField(blank=True, null=True)
    created = models.DateTimeField(editable=False, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)
    is_email_activate = models.BooleanField(default=False)
    is_phone_activate = models.BooleanField(default=False)
    
    objects = models.Manager()
    user = UserManager()

    def get_date_dict(self):
        date_dict = defaultdict(list)
        photos = self.photos.order_by('exif_datetime_original').distinct('exif_datetime_original')

        for photo in photos:
            # remove duplicated month
            if not date_dict or not date_dict.get(photo.exif_datetime_original.year):
                date_dict[photo.exif_datetime_original.year].append(photo.exif_datetime_original)
            else:
                for date in date_dict.get(photo.exif_datetime_original.year):
                    if photo.exif_datetime_original.month == date.month:
                        break;
                    date_dict[photo.exif_datetime_original.year].append(photo.exif_datetime_original)

        return date_dict.items()

    def get_date(self, year, month):
        return "test111"

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.auth_user.username

photo/templates/base.html
<html>
    {% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block head %}{% endblock %}
    </head>
    <body>
        {% block header %}
        {% endblock %}
        {% block content %}
        {% endblock %}
        {% block footer %}
        {% endblock %}
    </body>
<html>

photo/templates/child_gallery.html
{% load static %}
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="{% static 'css/lightgallery.css' %}" /> 
        <!-- jQuery version must be >= 1.8.0; -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

        <!-- A jQuery plugin that adds cross-browser mouse wheel support. (Optional) -->
        <script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>

        <script src="{% static 'js/lightgallery-all.js' %}"></script>

        <!-- lightgallery plugins -->
        <script src="{% static 'js/lg-thumbnail.js' %}"></script>
        <script src="{% static 'js/lg-fullscreen.js' %}"></script>
    </head>
    <body>
        {% if photo_dict %}
            {% for key, photos in photo_dict %}
                {% if photos %}
                <div>{{key}}</div>
                <div id="lightgallery{{key}}">
                    {% for photo in photos %}
                    <a id="{{photo.exif_datetime_original | date:'Y-m-d'}}" name="{{photo.get_age_description}}" href="{{ photo.get_url }}">
                        <img src="{{ photo.get_thumbnail_url }}" />
                    </a>
                    {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <script type="text/javascript">
            $(document).ready(function() {
                {% for key, photos in photo_dict %}
                    {% if photos %}
                    $("#lightgallery{{key}}").lightGallery(); 
                    {% endif %}
                {% endfor %}
            });
        </script>
    </body>
<html>

photo/templates/date_archive_gallery.html
{% extends "user_gallery.html" %}
{% load static %}
{% block content %}        
    <h1>{{title}}</h1>
    <div id="lightgallery">
        {% for photo in object_list %}
        <a id="{{photo.exif_datetime_original}}" href="{{ photo.get_image_url }}">
            <img src="{{ photo.get_thumbnail_url }}" />
        </a>
        {% endfor %}
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#lightgallery").lightGallery(); 
        });
    </script>
{% endblock %}

photo/templates/galleries.html
{% extends "base.html" %}
{% load static %}
{% block head %}        
    <link type="text/css" rel="stylesheet" href="{% static 'css/lightgallery.css' %}" /> 

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- A jQuery plugin that adds cross-browser mouse wheel support. (Optional) -->
    <script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>

    <script src="{% static 'js/lightgallery-all.js' %}"></script>

    <!-- lightgallery plugins -->
    <script src="{% static 'js/lg-thumbnail.js' %}"></script>
    <script src="{% static 'js/lg-fullscreen.js' %}"></script>
{% endblock %}
{% block content %}        
    {% for gallery in object_list %}
    <div>{{gallery.title}}</div>
    <div id="lightgallery{{gallery.title}}">
        {% for photo in gallery.photo_set.all %}
        {% if gallery.date_format == "1" %}
        <a id="{{photo.exif_datetime_original}}" href="{{ photo.get_image_url }}">
        {% elif gallery.date_format == "2" %}
        <a id="{{photo.get_age_description}}" href="{{ photo.get_image_url }}">
        {% elif gallery.date_format == "3" %}
        <a id="{{photo.exif_datetime_original}}" name="{{photo.get_age_description}}" href="{{ photo.get_image_url }}">
        {% else %}
        <a href="{{ photo.get_image_url }}">
        {% endif %}
            <img src="{{ photo.get_thumbnail_url }}" />
        </a>
        {% endfor %}
    </div>
    {% endfor %}

    <script type="text/javascript">
        $(document).ready(function() {
            {% for gallery in object_list %}
                $("#lightgallery{{gallery.title}}").lightGallery(); 
            {% endfor %}
        });
    </script>
{% endblock %}

photo/templates/gallery.html
{% extends "base.html" %}
{% load static %}
{% block head %}        
    <link type="text/css" rel="stylesheet" href="{% static 'css/lightgallery.css' %}" /> 

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- A jQuery plugin that adds cross-browser mouse wheel support. (Optional) -->
    <script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>

    <script src="{% static 'js/lightgallery-all.js' %}"></script>

    <!-- Image Picker -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/image-picker.css' %}" /> 
    <script src="{% static 'js/image-picker.js' %}"></script>

    <!-- lightgallery plugins -->
    <script src="{% static 'js/lg-thumbnail.js' %}"></script>
    <script src="{% static 'js/lg-fullscreen.js' %}"></script>

    <!-- jquery dialog -->
    <script src="{% static 'js/jquery-ui-1.12.1.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'css/jquery-ui-1.12.1.css' %}" /> 

    <script>
        $(function() {
            var dialog, form;

            dialog = $("#dialog-form").dialog({
                autoOpen: false,
                height: 720,
                width: "80%",
                modal: true,
                buttons: {
                    "确定": addImages,
                    "取消": function() {
                        resetImagePicker();
                    }
                },
                close: function() {
                    resetImagePicker();
                }
            });

            form = dialog.find("form").on("submit", function(event) {
            });

            $("#add-image").button().on("click", function() {
                dialog.dialog("open");
            });

            function addImages() {
                var selected_images = $("div[class='thumbnail selected']").children('img');
                for (var i = 0; i < selected_images.length; i++) {
                    var selected_val = $("#selected_images").val();
                    if (selected_val) {
                        $("#selected_images").val(selected_val + "," + selected_images[i].alt);
                    } else {
                        $("#selected_images").val(selected_images[i].alt);
                    }
                }

                resetImagePicker();
                if (selected_images.length > 0) {
                    form.submit();
                }

                return true;
            }

            function resetImagePicker() {
                form[0].reset();
                $("select").imagepicker({
                    hide_select: true,
                    show_label: false,
                    initialized: undefined,
                    changed: undefined,
                    clicked: undefined,
                    selected: undefined,
                });

                dialog.dialog("close");
            }

            resetImagePicker();

            $("#lightgallery").lightGallery(); 
        });
    </script>
{% endblock %}
{% block content %}        
    <h1>{{title}}</h1>
    <button id="add-image">编辑照片</button></br></br>
    <div id="dialog-form" title="编辑照片" style="display: none;">
        <form method="post">{% csrf_token %}
            <input type="hidden" name="selected_images" id="selected_images" value="" />
            <fieldset>
                <select multiple="multiple" class="image-picker">
                    {% for photo in object_list %}
                    <option data-img-alt="{{photo.id}}" data-img-src="{{photo.get_thumbnail_url}}" value="{{photo.id}}" selected="selected">{{photo.name}}</option>
                    {% endfor %}
                    {% for photo in other_photos %}
                    <option class="thumbnail selected" data-img-alt="{{photo.id}}" data-img-src="{{photo.get_thumbnail_url}}" value="{{photo.id}}">{{photo.name}}</option>
                    {% endfor %}
                </select>
            </fieldset>
        </form>
    </div>
    <div id="lightgallery">
        {% for photo in object_list %}
        {% if gallery.date_format == "1" %}
        <a id="{{photo.exif_datetime_original}}" href="{{ photo.get_image_url }}">
        {% elif user.date_format == "2" %}
        <a id="{{photo.get_age_description}}" href="{{ photo.get_image_url }}">
        {% elif user.date_format == "3" %}
        <a id="{{photo.exif_datetime_original}}" name="{{photo.get_age_description}}" href="{{ photo.get_image_url }}">
        {% else %}
        <a href="{{ photo.get_image_url }}">
        {% endif %}
            <img src="{{ photo.get_thumbnail_url }}" />
        </a>
        {% endfor %}
    </div>
{% endblock %}

photo/templates/index.html
{% load static %}
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="{% static 'css/lightgallery.css' %}" /> 
        <!-- jQuery version must be >= 1.8.0; -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

        <!-- A jQuery plugin that adds cross-browser mouse wheel support. (Optional) -->
        <script src="{% static 'js/jquery.mousewheel.min.js' %}"></script>

        <script src="{% static 'js/lightgallery-all.js' %}"></script>

        <!-- lightgallery plugins -->
        <script src="{% static 'js/lg-thumbnail.js' %}"></script>
        <script src="{% static 'js/lg-fullscreen.js' %}"></script>
    </head>
    <body>
        {% if photo_dict %}
            {% for key, photos in photo_dict %}
                {% if photos %}
                <div>{{key}}</div>
                <div id="lightgallery{{key}}">
                    {% for photo in photos %}
                    <a id="{{photo.exif_datetime_original | date:'Y-m-d H:i:s'}}" name="{{photo.get_age_description}}" href="{{ photo.get_url }}">
                        <img src="{{ photo.get_thumbnail_url }}" />
                    </a>
                    {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <script type="text/javascript">
            $(document).ready(function() {
                {% for key, photos in photo_dict %}
                    {% if photos %}
                    $("#lightgallery{{key}}").lightGallery(); 
                    {% endif %}
                {% endfor %}
            });
        </script>
    </body>
<html>

photo/templates/users.html
{% extends "base.html" %}

{% block head %}
<style type="text/css">
a {
    text-decoration: none;
}

tr td {
    font-size: 24px; padding: 8px 0px 0px 0px; width: 40%;
}

a li {
    padding: 8px 0px 0px 0px;
}

a div {
    font-size: 20px; padding: 8px 0px 0px 0px;
}
</style>
{% endblock %}

{% block content %}        
    {% for message in messages %}
    <div>{{ message }}</div>
    {% endfor %}
    {% for user in object_list %}
    <table width="100%">
        <tr>
            <td>
                <a href="{% url 'photo:user-gallery' user.id%}">
                    {{user.auth_user.username}}
                </a>
            </td>
            <td>
                <a href="{% url 'photo:classification' user.id %}">
                    Init
                </a>
            </td>
            <td>
                <a href="{% url 'photo:reset' user.id %}">
                    Reset
                </a>
            </td>
        </tr>
    </table>
    {% for year, dates in user.get_date_dict %}
        <a href="{% url 'photo:gallery-year-archive' user.id year %}">
            <div>{{year}}</div>
        </a>
        {% for d in dates %}
            <a href="{% url 'photo:gallery-month-archive' user.id year d.month %}">
                <li>{{d|date:'M, Y'}}</li>
            </a>
        {% endfor %}
    {% endfor %}</br></br>
    {% endfor %}
    <a href="{% url 'photo:galleries' %}">
        <div>相册</div>
    </a>
    {% for gallery in galleries %}
        <a href="{% url 'photo:gallery' gallery.title %}">
            <li>{{gallery.title}}</li>
        </a>
    {% endfor %}</br>
{% endblock %}